### ISSUE TITLE
Error: No jar URL found for version '4.0.5' in versions.json

### ISSUE THREAD

**Issue by HenrryVargas** [neo4j-contrib/neo4j-helm#29] opened 2020-06-23 09:03 UTC
Hi

 I run

**helm install -n mygraph https://github.com/neo4j-contrib/neo4j-helm/releases/download/4.0.5-1/neo4j-4.0.5-1.tgz --set acceptLicenseAgreement=yes --set neo4jPassword=nanana** 

**And I get this error:**

Configuration override prefix = mygraph_neo4j_core_2
Starting Neo4j CORE 2 on mygraph-neo4j-core-2.mygraph-neo4j.neo4j.svc.cluster.local
Changed password for user 'neo4j'.
Fetching versions.json for Plugin 'apoc' from https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json
Error: No jar URL found for version '4.0.5' in versions.json from 'https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json'

**Comment by moxious** [comment] 2020-06-23 12:18
I cannot replicate this.   When I do the same thing, it installs fine and includes APOC:

![Screen Shot 2020-06-23 at 8 16 47 AM](https://user-images.githubusercontent.com/5471710/85402637-00821380-b52a-11ea-8791-a1f54f303b46.png)

What version of helm are you using?    The `-n` flag is not used in the more recent versions.

**Comment by moxious** [comment] 2020-06-23 12:40
Is it possible that your pods don't have access to the internet to grab https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json

?

**Comment by moxious** [comment] 2020-06-26 12:57
Because neo4j 4.0.5 is not that old, I'm guessing another possibility is that you *could* fetch that URL, but that the right entry in that JSON file hadn't been updated for the neo4j 4.0.5 release as of that moment. 

If you try your deploy again and you can't replicate this problem (which seems likely) then that could've been the cause.

**Comment by moxious** [comment] 2020-06-29 16:37
Closing this issue because of lack of follow-up, and an inability to reproduce.   Please re-open it if you can replicate.

**Closed by moxious** 2020-06-29 16:37 UTC
