### ISSUE TITLE
podAnnnotations with Boolean in Map do not work

### ISSUE THREAD

**Issue by mohammadsrahman** [neo4j-contrib/neo4j-helm#65] opened 2020-07-30 16:36 UTC
I am trying to add in an annotation as follows:

```
neo4j:
    podAnnotations:
        - sidecar.istio.io/inject: "false"
```

But the Go templates are complaining the formatting is incorrect.

See line below for contributing failure.

https://github.com/neo4j-contrib/neo4j-helm/blob/cce71f37c28a024c66b5bb0b761e20eb6d99c356/values.yaml#L34

**Comment by moxious** [comment] 2020-08-07 13:54
This issue is caused by improper inclusion of the values in the resulting YAML template.  Working on a fix right now.

**Comment by moxious** [comment] 2020-08-07 14:03
Related PR: https://github.com/neo4j-contrib/neo4j-helm/pull/73

**Comment by moxious** [comment] 2020-08-07 14:05
A different issue is that the top level "neo4j" key isn't needed, and the podAnnotations should be expressed as a MAP not as an array item as is given in this ticket.

See the `deployment-scenarios/cluster-custom-labels-annotations.yaml` example that is in the PR as an example of how to set custom labels & annotations correctly in a way that works.

**Comment by moxious** [comment] 2020-08-07 14:47
Closed by PR referenced above.

**Closed by moxious** 2020-08-07 14:47 UTC
Labels: bug
