### ISSUE TITLE
Cluster cannot connect to extra core, replica after scaling up

### ISSUE THREAD

**Issue by bugzyz** [neo4j-contrib/neo4j-helm#48] opened 2020-07-13 13:06 UTC
Hi! 

We used command `kubectl scale statefulsets testzyz2-neo4j-core --replicas=5` to scale the original cluster with 3 cores to 5 cores. 

After scaling, the new cores' pod is running but not ready. We saw this log in old core's logs/debug.log:"failed because of java.net.UnknownHostException: discovery-my-neo4j-neo4j-3.default.svc.cluster.local". 

It seems that the extra cores created by the scale commands didn’t have a corresponding discovery service(ClusterIP). So our colleague just manually wrote the yaml file and create the discovery service and then it works.

Did we make a mistake on the configuration?

**Comment by moxious** [comment] 2020-07-13 13:54
We are looking into this one internally.  (I believe I'm in contact with you on on our internal slack.  ;) 

Root cause so far seems to be this:

* Cores 1 - 3 are running just fine
* Cores 4, 5 start up, attempt to connect to cores 1 - 3.   Cores 1 - 3 *fail DNS resolution* on the addresses that are contacing them, and so do not allow them to join the cluster
* Cores 4 and 5 eventually give up.

The DNS resolution is provided for by the discovery service, which in turn targets particular labels in the statefulset.  This _should be quite fast_ but it appears there may be a race condition between how quickly the new pods can start up, and how quickly the discovery service publishes their addresses.

Internal engineering suggests passing `-Dnetworkaddress.cache.negative.ttl` and `-Dakka.io.dns.inet-address.negative-ttl=never` as arguments to the JVM.   The purpose here is to disable DNS caching.  The idea is that cores 0, 1, 2 fail DNS, cache the failed answer, and then can't get the right address even when the discovery service does later publish them.   The hope is that if you disable DNS caching in this way, the first lookup might fail, but after the discovery service catches up the cluster would form regularly.

The scaling operation has been tested separately, and we weren't able to replicate this problem -- but that would make sense.  If it's a DNS race condition, it could be happening for you and not for me.

So this is what I'd try next.

To pass JVM args, you have to use the dbms.jvm.additional config, as shown here: https://github.com/neo4j-contrib/neo4j-helm/blob/master/templates/common-configmap.yaml#L24

**Comment by moxious** [comment] 2020-07-13 16:13
@bugzyz experimenting with this, there's a different potential problem. 

The discovery service gets created n times where n is the number of up-front configured cores here:

https://github.com/neo4j-contrib/neo4j-helm/blob/master/templates/discovery-lb.yaml#L5

I think we need to create extras, because this doesn't auto-scale, but it needs to, when you scale the core.

**Comment by moxious** [comment] 2020-07-13 16:28
This is a sample PR which I think solves the issue.  The main fix is the expanded number of discovery LB services that get created.  This in turn "pre-scales" the available DNS.   Not sure yet this is the best solution, but I can confirm that I can replicate your issue, and this PR does fix it.  I'll keep thinking to see if there's a better way to do this.

https://github.com/neo4j-contrib/neo4j-helm/pull/50

**Comment by bugzyz** [comment] 2020-07-14 07:00
Ha! Nice to meet you @moxious outside of slack! :)

We tried the #51 PR and yes, it does work for scaling up the cluster with 3 cores to 5 cores. But there is a problem that we will have 5 discovery service even we only need 1 core for the cluster. And further more, the situation will still exist when user try to scale up 5 cores to 7 cores cuz there's only 5 discovery services. 

Looking forward to your better way to solve this problem:)

**Comment by bugzyz** [comment] 2020-07-14 07:04
Btw, will the same problem occur when user scale up the number of read-replica?

**Comment by moxious** [comment] 2020-07-14 11:19
@bugzyz couple of points:

- Lacking special circumstances, I wouldn't ever recommend scaling from 5 to 7 cores.  There's a time and a place for 7+ core members in Neo4j, and it's usually when you have a multi-geographic cluster.  The idea behind having so many core nodes is that you can have a total geo failure, and still have enough nodes left over to keep running your cluster in HA.   Within a *single k8s cluster* you're going to be pinned to one geography I think (unless you get really fancy and add a second node pool in another geography and then add lots of extra stuff to schedule part of your statefulset into that other node pool, which I'm not even sure how to do).   If you're pinned to one geography (my assumption) then scaling to 7 cores probably won't make sense.  The more core nodes you have the slower your writes must get (neo4j ensures transactional durability by confirming each write with a majority of the cluster; the more members in the cluster, the bigger the majority is, and the longer to confirm writes).  You probably won't get a lot of extra HA out of going to 7 core members, but you would be spending more on infra and slowing write speeds.

That being said, I could be wrong -- if you have a specific requirement that you need to go to 7, then I could make the number of extra duplicate services configurable.  ;)

RE: read replicas -- none of this affects those.  The discovery service (that which services port 5000, 6000, 7000 for internal cluster replication) is the one that we're scaling here.  When a new read replica joins the cluster, it just contacts the discovery service using the k8s discovery mechanism, and starts replicating from there.   Read replicas contact core members and do TX replication to get a copy of the data -- but in neo4j language "they don't participate in cluster topology" meaning that the cores don't really need to know how many read replicas there are, they aren't "discoverable" so they can come and go as they please, and this scaling issue we're discussing doesn't impact read replicas at all.

**Comment by moxious** [comment] 2020-07-15 11:56
I've merged the associated and PR and will close this issue for now.  The fix addresses this particular problem, and the problem shouldn't occur for read replicas.  It's true that the fix does not address the case of scaling cores up to 7+.  Let's take that up as a separate issue when/if it's identified that such large core sizes are actually appropriate for the deployment.

**Closed by moxious** 2020-07-15 11:56 UTC
